[tool.poetry]
name = "geographica-longitude"
packages = [
    { include='longitude' }
]
version = "1.0.0a1"
description = ""
homepage = "https://github.com/GeographicaGS/Longitude"
authors = [
    "Geographica <system@geographica.com>",
    "Dani Ramirez <daniel.ramirez@geographica.com>"
]
license = "MIT"
readme = "README.md"
exclude = [
    "longitude/core/tests/**",
    "longitude/core/**/README.md"
]

[tool.poetry.dependencies]
carto = "1.4"
python = "^3.6"
redis = "3.1"
psycopg2-binary = "2.7.7"
sqlalchemy = "1.3.0b2"
cartoframes = "^0.9.0"
shapely = "^1.6"
pandas = "^0.24.1"
apispec = "^0.39.0"
inflect = "^2.1"
flask = "^1.0"
flasgger = "^0.9.2"
flask_cors = "^3.0"
marshmallow = {version = "^2.18",allows-prereleases = true}

[tool.poetry.dev-dependencies]
pdoc = "^0.3.2"
pylint = "^2.2"
coverage = "^4.5"
pytest-cov = "^2.6"
pytest-xdist = "^1.26"
pytest-sugar = "^0.9.2"
pytest-instafail = "^0.4.0"

[tool.flit.metadata.urls]
Company = "https://geographica.com"
Repository = "https://github.com/GeographicaGS/Longitude"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
